### ISSUE TITLE
우와~ 관심이 많습니다. 적용 가능한 환경이 어떻게 되나요? - What is the requirements?

### ISSUE THREAD

**Issue by jongkwang** [iodes/InteractiveLogin#2]
적용 가능한 환경이 어떻게 되나요?
C# 환경에서만 가능한가요?

----

In what environment does it work?
Only work in C#?

**Comment by iodes** [comment]
현재 버전은 DirectX 기반의 렌더러로 Windows C# WPF 환경에서 동작하고 있습니다.

Live2D Cubism엔진 자체는 게임 엔진인 Unity와 호환되며 그 이외에도 SDK를 통해서
WebGL + HTML5를 통한 웹 및 모바일 환경에 대응하고 있기 때문에 본 소스의 렌더링
로직을 웹 프론트엔드 환경에 맞게 변환하게되면 웹 환경에서도 사용이 가능합니다.

Live2D WebGL SDK : http://sites.cybernoids.jp/cubism2/sdk_tutorial/platform-setting/webgl
Live2D WebGL Sample : http://app2.live2d.com/a/wg/ie.html
